import { MenuItem, TranslationSet } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // --- PIZZAS ---
  {
    id: 'pizza-margherita',
    nameEn: 'Pizza Margherita',
    nameSq: 'Pica Margherita',
    descriptionSq: 'Salcë, mozzarella',
    descriptionEn: 'Tomato sauce, mozzarella cheese',
    priceMedium: 350,
    priceFamily: 600,
    category: 'pizza',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeR1m9Riwlo0c0_dLHbf4Yut9Mg3IshhEt_g&s',
    tagsEn: ['Classic', 'Vegetarian'],
    tagsSq: ['Klasike', 'Vegjetariane'],
    isPopular: true
  },
  {
    id: 'pizza-sallam',
    nameEn: 'Pizza Salami',
    nameSq: 'Pica Sallam',
    descriptionSq: 'Salcë, mozzarella, sallam',
    descriptionEn: 'Tomato sauce, mozzarella, salami',
    priceMedium: 400,
    priceFamily: 750,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/367915/pexels-photo-367915.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Meat'],
    tagsSq: ['Me Mish']
  },
  {
    id: 'pizza-proshute',
    nameEn: 'Pizza Ham',
    nameSq: 'Pica Proshutë',
    descriptionSq: 'Salcë, mozzarella, proshutë',
    descriptionEn: 'Tomato sauce, mozzarella, cooked ham',
    priceMedium: 450,
    priceFamily: 800,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Italian Style'],
    tagsSq: ['Stil Italian']
  },
  {
    id: 'pizza-proshute-krudo',
    nameEn: 'Pizza Prosciutto Crudo',
    nameSq: 'Pica Proshutë Krudo',
    descriptionSq: 'Salcë, mozzarella, proshutë krudo',
    descriptionEn: 'Tomato sauce, mozzarella, authentic crudo prosciutto',
    priceMedium: 600,
    priceFamily: 1100,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/2619970/pexels-photo-2619970.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Premium', 'Crudo'],
    tagsSq: ['Premium', 'Krudo'],
    isPopular: true
  },
  {
    id: 'pizza-kerpudhe',
    nameEn: 'Pizza Mushroom',
    nameSq: 'Pica Kërpudhë',
    descriptionSq: 'Salcë, mozzarella, kërpudhë',
    descriptionEn: 'Tomato sauce, mozzarella, wild mushrooms',
    priceMedium: 400,
    priceFamily: 750,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1435896/pexels-photo-1435896.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Vegetarian'],
    tagsSq: ['Vegjetariane']
  },
  {
    id: 'pizza-proshute-sallam',
    nameEn: 'Pizza Ham & Salami',
    nameSq: 'Pica Proshutë Sallam',
    descriptionSq: 'Salcë, mozzarella, proshutë, sallam',
    descriptionEn: 'Tomato sauce, mozzarella, cooked ham, premium salami',
    priceMedium: 450,
    priceFamily: 800,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/803290/pexels-photo-803290.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Rich Meat'],
    tagsSq: ['Me Shumë Mish']
  },
  {
    id: 'pizza-proshute-kerpudhe',
    nameEn: 'Pizza Ham & Mushroom',
    nameSq: 'Pica Proshutë Kërpudhë',
    descriptionSq: 'Salcë, mozzarella, proshutë, kërpudhë',
    descriptionEn: 'Tomato sauce, mozzarella, ham, fresh mushrooms',
    priceMedium: 500,
    priceFamily: 900,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/842519/pexels-photo-842519.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Classic Choice'],
    tagsSq: ['Zgjedhje Klasike'],
    isPopular: true
  },
  {
    id: 'pizza-proshute-krudo-kerpudhe',
    nameEn: 'Pizza Prosciutto Crudo & Mushroom',
    nameSq: 'Pica Proshutë Krudo Kërpudhë',
    descriptionSq: 'Salcë, mozzarella, proshutë krudo, kërpudhë',
    descriptionEn: 'Tomato sauce, mozzarella, premium crudo, mushrooms',
    priceMedium: 650,
    priceFamily: 1200,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/10496207/pexels-photo-10496207.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Gourmet'],
    tagsSq: ['Gustatore']
  },
  {
    id: 'pizza-kapricosa',
    nameEn: 'Pizza Capriccosa',
    nameSq: 'Pica Kapricosa',
    descriptionSq: 'Salcë, mozzarella, proshutë, sallam, kërpudhë, ullinj',
    descriptionEn: 'Tomato sauce, mozzarella, ham, salami, mushrooms, black olives',
    priceMedium: 500,
    priceFamily: 900,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1653877/pexels-photo-1653877.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Fully Loaded', 'Popular'],
    tagsSq: ['E Plotë', 'Më e Shitura'],
    isPopular: true
  },
  {
    id: 'pizza-kapricosa-krudo',
    nameEn: 'Pizza Capriccosa Crudo',
    nameSq: 'Pica Kapricosa Krudo',
    descriptionSq: 'Salcë, mozzarella, proshutë krudo, kërpudhë, ullinj',
    descriptionEn: 'Tomato sauce, mozzarella, prosciutto crudo, mushrooms, olives',
    priceMedium: 700,
    priceFamily: 1350,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/10790638/pexels-photo-10790638.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Royal', 'Exclusive'],
    tagsSq: ['Mbretërore', 'Ekskluzive']
  },
  {
    id: 'pizza-katër-stinet',
    nameEn: 'Pizza 4 Seasons (4 Stinët)',
    nameSq: 'Pica 4 Stinët',
    descriptionSq: 'Salcë, mozzarella, proshutë, sallam, kërpudhë, ton',
    descriptionEn: 'Tomato sauce, mozzarella, ham, salami, mushrooms, gourmet tuna',
    priceMedium: 500,
    priceFamily: 900,
    category: 'pizza',
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Pizza_Quattro_Stagioni_01.jpg',
    tagsEn: ['Traditional'],
    tagsSq: ['Tradicionale']
  },
  {
    id: 'pizza-katër-djathrat',
    nameEn: 'Pizza 4 Cheeses (4 Djathrat)',
    nameSq: 'Pica 4 Djathrat',
    descriptionSq: 'Salcë, mozzarella, gorgonxola, guda, djathë i bardhë',
    descriptionEn: 'Tomato sauce, mozzarella, gorgonzola, gouda, white chesses',
    priceMedium: 450,
    priceFamily: 800,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/2702674/pexels-photo-2702674.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Cheese Lovers'],
    tagsSq: ['Pasioni i Djathtit']
  },
  {
    id: 'pizza-tonno',
    nameEn: 'Pizza Tuna (Tonno)',
    nameSq: 'Pica Tonno',
    descriptionSq: 'Salcë, mozzarella, ton, speca, ullinj',
    descriptionEn: 'Tomato sauce, mozzarella, premium tuna, sweet peppers, olives',
    priceMedium: 500,
    priceFamily: 900,
    category: 'pizza',
    image: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Pizza_with_tuna%2C_red_onion_and_capers%2C_by_S%C3%B6ren_Kelsey.jpg',
    tagsEn: ['Marine Taste'],
    tagsSq: ['Shije Deti']
  },
  {
    id: 'pizza-tonno-kerpudhe',
    nameEn: 'Pizza Tuna & Mushroom',
    nameSq: 'Pica Tonno Kërpudhë',
    descriptionSq: 'Salcë, mozzarella, ton, kërpudhë',
    descriptionEn: 'Tomato sauce, mozzarella, premium tuna, mushrooms',
    priceMedium: 550,
    priceFamily: 950,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Savory'],
    tagsSq: ['Shijshme']
  },
  {
    id: 'pizza-tonno-proshute',
    nameEn: 'Pizza Tuna & Ham',
    nameSq: 'Pica Tonno Proshutë',
    descriptionSq: 'Salcë, mozzarella, proshutë, ton',
    descriptionEn: 'Tomato sauce, mozzarella, cooked ham, premium tuna',
    priceMedium: 550,
    priceFamily: 1000,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1166120/pexels-photo-1166120.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Special Mix'],
    tagsSq: ['Kombinim Special']
  },
  {
    id: 'pizza-mix',
    nameEn: 'Pizza Mix',
    nameSq: 'Pica Mix',
    descriptionSq: 'Salcë, mozzarella, ton, kërpudhë, ullinj, sallam pikant, speca',
    descriptionEn: 'Tomato sauce, mozzarella, tuna, mushrooms, olives, spicy salami, bell peppers',
    priceMedium: 600,
    priceFamily: 1150,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Super Mixed'],
    tagsSq: ['E Kombinuar Plotësisht'],
    isPopular: true
  },
  {
    id: 'pizza-vegjetariane',
    nameEn: 'Pizza Vegetariana',
    nameSq: 'Pica Vegjetariane',
    descriptionSq: 'Salcë, mozzarella, domate, speca, ullinj',
    descriptionEn: 'Tomato sauce, mozzarella, fresh tomatoes, crisp bell peppers, black olives',
    priceMedium: 450,
    priceFamily: 750,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1435900/pexels-photo-1435900.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Healthy', 'Vegetarian'],
    tagsSq: ['E Shëndetshme', 'Vegjetariane']
  },
  {
    id: 'pizza-pikante',
    nameEn: 'Pizza Diavola (Pikante)',
    nameSq: 'Pica Pikante',
    descriptionSq: 'Salcë, mozzarella, sallam pikant, speca, ullinj',
    descriptionEn: 'Tomato sauce, mozzarella, spicy Italian salami, bell peppers, olives',
    priceMedium: 500,
    priceFamily: 900,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Fuego', 'Spicy'],
    tagsSq: ['Flakë', 'Pikante'],
    isPopular: true
  },
  {
    id: 'pizza-peperoni',
    nameEn: 'Pizza Pepperoni',
    nameSq: 'Pica Pepperoni',
    descriptionSq: 'Salcë, mozzarella, peperoni',
    descriptionEn: 'Tomato sauce, mozzarella, authentic Italian pepperoni slices',
    priceMedium: 550,
    priceFamily: 1000,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/803290/pexels-photo-803290.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Traditional Pepperoni'],
    tagsSq: ['Peperoni Tradicional']
  },
  {
    id: 'pizza-shtepie',
    nameEn: 'Homemade Style Pizza (Shtëpie)',
    nameSq: 'Pica Shtëpie',
    descriptionSq: 'Salcë, mozzarella, djathë i bardhë, domate, speca, proshutë',
    descriptionEn: 'Tomato sauce, mozzarella, soft white Albanian cheese, fresh tomatoes, peppers, cooked ham',
    priceMedium: 500,
    priceFamily: 900,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Local Touch'],
    tagsSq: ['Tradita Shqiptare']
  },
  {
    id: 'pizza-la-crema',
    nameEn: 'Pizza La Crema',
    nameSq: 'Pica La Crema',
    descriptionSq: 'Salcë, mozzarella, pana, proshutë, sallam, sallam pikant, kërpudhë',
    descriptionEn: 'Tomato sauce, mozzarella, heavy cooking cream, cooked ham, salami, spicy salami, fresh mushrooms',
    priceMedium: 550,
    priceFamily: 950,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/2702674/pexels-photo-2702674.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Extra Creamy'],
    tagsSq: ['Shtresë Krem']
  },
  {
    id: 'pizza-la-crema-krudo',
    nameEn: 'Pizza La Crema Crudo',
    nameSq: 'Pica La Crema Krudo',
    descriptionSq: 'Salcë, mozzarella, pana, proshutë krudo, sallam pikant, kërpudhë',
    descriptionEn: 'Tomato sauce, mozzarella, cooking cream, prosciutto crudo, spicy salami, fresh mushrooms',
    priceMedium: 750,
    priceFamily: 1400,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/10496207/pexels-photo-10496207.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Luxury Cheese & Crudo'],
    tagsSq: ['E Pasur e Krudo']
  },
  {
    id: 'pizza-italia',
    nameEn: 'Pizza Italia Special',
    nameSq: 'Pica Italia',
    descriptionSq: 'Salcë, proshutë, sallam, mozzarella, pana',
    descriptionEn: 'Tomato sauce, premium ham, fine salami, melting mozzarella, light cooking cream',
    priceMedium: 500,
    priceFamily: 850,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/11115711/pexels-photo-11115711.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Signature', 'House Special'],
    tagsSq: ['Shtëpisë', 'Specialiteti ynë'],
    isPopular: true
  },
  {
    id: 'pro-pizza',
    nameEn: 'PRO Pizza Extra',
    nameSq: 'PRO Pica',
    descriptionSq: 'Salcë, mozzarella, gorgonxola, sallam, peperoni, pana',
    descriptionEn: 'Tomato sauce, rich mozzarella, gorgonzola cheese, premium salami, pepperoni, heavy cream',
    priceMedium: 700,
    priceFamily: 1300,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Executive Choice'],
    tagsSq: ['Zgjedhje E Parë'],
    isPopular: true
  },
  {
    id: 'pizza-mediteriane',
    nameEn: 'Pizza Mediteriane',
    nameSq: 'Pica Mediteriane',
    descriptionSq: 'Salcë, mozzarella, sallam pikant, ton',
    descriptionEn: 'Tomato sauce, mozzarella, pepperoni/spicy salami, delicious tuna',
    priceMedium: 600,
    priceFamily: 1000,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1653877/pexels-photo-1653877.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Mediterranean Duo'],
    tagsSq: ['Dyshja Mesdhetare']
  },
  {
    id: 'pizza-primavera',
    nameEn: 'Pizza Primavera',
    nameSq: 'Pica Primavera',
    descriptionSq: 'Salcë, mozzarella, rukola, pomodorini, proshutë krudo, djathë grana, vaj ulliri',
    descriptionEn: 'Tomato sauce, mozzarella, fresh wild baby arugula, cherry tomatoes, prosciutto crudo, shaved grana padano cheese, olive oil',
    priceMedium: 700,
    priceFamily: 1350,
    category: 'pizza',
    image: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizza_Prosciutto_e_Rucola_in_G%C3%B6teborg.jpg',
    tagsEn: ['Gourmet Garden'],
    tagsSq: ['Kopshti i Shijes'],
    isPopular: true
  },
  {
    id: 'pizza-ime',
    nameEn: 'My Pizza (Ime)',
    nameSq: 'Pica Ime',
    descriptionSq: 'Pana, kërpudhë, mozzarella, gorgonxola',
    descriptionEn: 'Cooking cream base, wild mushrooms, mozzarella, fine blue gorgonzola cheese',
    priceMedium: 600,
    priceFamily: 900,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/2702674/pexels-photo-2702674.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['White Pizza'],
    tagsSq: ['Pica e Bardhë']
  },
  {
    id: 'pizza-chicken',
    nameEn: 'Pizza Chicken',
    nameSq: 'Pica Chicken',
    descriptionSq: 'Salcë, mozzarella, fileto pule',
    descriptionEn: 'Tomato sauce, premium mozzarella, roasted chicken breast tender slices',
    priceMedium: 550,
    priceFamily: 1000,
    category: 'pizza',
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Pizza_Chicken_Tikka.jpg',
    tagsEn: ['Protein Packed'],
    tagsSq: ['E Pasur me Proteinë']
  },
  {
    id: 'pizza-chicken-pana',
    nameEn: 'Pizza Chicken Pana Cream',
    nameSq: 'Pica Chicken Pana',
    descriptionSq: 'Mozzarella, fileto pule, djath i bardhë, pana, domate',
    descriptionEn: 'Melting mozzarella, delicious chicken breast, white cheese, heavy cream base, fresh tomatoes',
    priceMedium: 600,
    priceFamily: 1150,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/2471171/pexels-photo-2471171.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Super Deluxe Chicken'],
    tagsSq: ['Mishi i Pulës Deluxe']
  },
  {
    id: 'pizza-chicken-garlic',
    nameEn: 'Pizza Chicken & Garlic Sauce',
    nameSq: 'Pica Chicken & Garlic sauce',
    descriptionSq: 'Salcë, mozzarella, fileto pule, salcë hudhre speciale',
    descriptionEn: 'Tomato sauce, premium mozzarella, grilled chicken slices, custom infused garlic cream sauce',
    priceMedium: 600,
    priceFamily: 1150,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Rich Flavor Burst'],
    tagsSq: ['Arome e Plotë']
  },
  {
    id: 'pizza-burn',
    nameEn: 'Pizza Burn (Super Hot)',
    nameSq: 'Pica Burn',
    descriptionSq: 'Salcë, mozzarella, peperoni, fileto pule, salcë hudhre pikante',
    descriptionEn: 'Tomato sauce, mozzarella, hot pepperoni slices, roasted chicken breast, spicy house garlic sauce',
    priceMedium: 750,
    priceFamily: 1450,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Super Spicy'],
    tagsSq: ['Jashtëzakonisht Pikante']
  },
  {
    id: 'pizza-tersina',
    nameEn: 'Pizza Tersina Tartufo',
    nameSq: 'Pica Tersina',
    descriptionSq: 'Salcë tartufi, mozzarella, peperoni, kërpudhë',
    descriptionEn: 'Luxurious black truffle cream sauce, mozzarella, high-grade pepperoni, wild mushrooms',
    priceMedium: 650,
    priceFamily: 1100,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1260968/pexels-photo-1260968.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Black Truffle', 'Aromatic'],
    tagsSq: ['Krem Zi Trufi', 'Aromatike'],
    isPopular: true
  },
  {
    id: 'pizza-tartufata',
    nameEn: 'Pizza Tartufata Crudo',
    nameSq: 'Pica Tartufata',
    descriptionSq: 'Salcë tartufi, mozzarella, proshute krudo, kërpudhë',
    descriptionEn: 'Black truffle cream sauce, mozzarella, authentic prosciutto crudo, mountain mushrooms',
    priceMedium: 700,
    priceFamily: 1350,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/10496207/pexels-photo-10496207.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Elite Choice', 'Truffle'],
    tagsSq: ['Kombinim Elitar', 'Truf']
  },
  {
    id: 'pizza-tartufami',
    nameEn: 'Pizza Tartufami Intense',
    nameSq: 'Pica Tartufami',
    descriptionSq: 'Salcë tartufi, mozzarella, peperoni, gorgonxola',
    descriptionEn: 'Aromatic truffle cream, rich mozzarella, pepperoni slices, intense gorgonxola chunks',
    priceMedium: 800,
    priceFamily: 1550,
    category: 'pizza',
    image: 'https://images.pexels.com/photos/1260968/pexels-photo-1260968.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Explosive Luxury'],
    tagsSq: ['Shije Absolute']
  },

  // --- SANDWICHES (All styled uniquely in their panel) ---
  {
    id: 'sand-sallam',
    nameEn: 'Salami Sandwich',
    nameSq: 'Sandwich Sallam',
    descriptionSq: 'majonezë, domate, ullinj, mozzarella, sallam',
    descriptionEn: 'mayonnaise, fresh tomato slices, sliced olives, mozzarella, premium salami',
    priceSq: 150,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1603901/pexels-photo-1603901.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['Klasik'],
    tagsEn: ['Classic']
  },
  {
    id: 'sand-proshute',
    nameEn: 'Ham Sandwich',
    nameSq: 'Sandwich Proshutë',
    descriptionSq: 'majonezë, domate, ullinj, mozzarella, proshutë',
    descriptionEn: 'mayonnaise, sweet tomatoes, black olives, mozzarella cheese, classic cooked ham',
    priceSq: 200,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1209029/pexels-photo-1209029.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['E Preferuar'],
    tagsEn: ['Top Choice'],
    isPopular: true
  },
  {
    id: 'sand-proshute-kerpudhe',
    nameEn: 'Ham & Mushroom Sandwich',
    nameSq: 'Sandwich Proshutë Kërpudhë',
    descriptionSq: 'majonezë, mozzarella, proshutë, kërpudhë',
    descriptionEn: 'creamy mayonnaise, soft mozzarella, savory cooked ham, sautéed mountain mushrooms',
    priceSq: 230,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1600891/pexels-photo-1600891.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 'sand-fshati',
    nameEn: 'Country Style Sandwich (Fshati)',
    nameSq: 'Sandwich Fshati',
    descriptionSq: 'majonezë, domate, ullinj, djathë i bardhë, sallam',
    descriptionEn: 'light mayo, rich tomatoes, local olives, organic soft white cheese, salami slices',
    priceSq: 170,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/580612/pexels-photo-580612.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['Fshati'],
    tagsEn: ['Traditional']
  },
  {
    id: 'sand-rukola',
    nameEn: 'Arugula & Mozzarella Sandwich',
    nameSq: 'Sandwich Rukola',
    descriptionSq: 'majonezë, domate, ullinj, mozzarella, djathë i bardhë, rukola',
    descriptionEn: 'mayonnaise, tomatoes, sliced olives, fresh mozzarella, traditional salad cheese, wild baby arugula',
    priceSq: 250,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['E Freskët'],
    tagsEn: ['Freshly Tossed']
  },
  {
    id: 'sand-tonno',
    nameEn: 'Classic Tuna Sandwich',
    nameSq: 'Sandwich Tonno',
    descriptionSq: 'majonezë, domate, ullinj, mozzarella, ton',
    descriptionEn: 'house mayo, fresh sweet tomatoes, rich olives, mozzarella, bonito shredded tuna',
    priceSq: 200,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1600891/pexels-photo-1600891.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 'sand-pikant',
    nameEn: 'Spicy Ventricina Sandwich',
    nameSq: 'Sandwich Pikant',
    descriptionSq: 'majonezë, domate, ullinj, mozzarella, sallam pikant',
    descriptionEn: 'mayonnaise, tomato, black olives, mozzarella, hot Italian fiery ventricina salami',
    priceSq: 230,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1603901/pexels-photo-1603901.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['Pikante'],
    tagsEn: ['Spicy']
  },
  {
    id: 'sand-katër-djathrat',
    nameEn: 'Four Cheese Feast Sandwich',
    nameSq: 'Sandwich 4 Djathrat',
    descriptionSq: 'majonezë, domate, ullinj, mozzarella, guda, gorgonxola, djathë i bardhë',
    descriptionEn: 'mayo, tomato slices, olives, mozzarella, melting gouda, rich gorgonzola, soft white cheese',
    priceSq: 200,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1209029/pexels-photo-1209029.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['4 Djathërat'],
    tagsEn: ['4 Cheeses']
  },
  {
    id: 'sand-la-crema',
    nameEn: 'La Crema Dream Sandwich',
    nameSq: 'Sandwich La Crema',
    descriptionSq: 'majonezë, domate, ullinj, mozzarella, sallam pikant, pana, kërpudhë',
    descriptionEn: 'mayo, tomatoes, black olives, mozzarella, fiery ventricina salami, light cream coat, mushrooms',
    priceSq: 250,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1128678/pexels-photo-1128678.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['Krem dhe Kërpurdhë'],
    tagsEn: ['Super Creamy']
  },
  {
    id: 'sand-ton-kerpudhe',
    nameEn: 'Tuna & Mushroom Sandwich',
    nameSq: 'Sandwich Ton Kërpudhë',
    descriptionSq: 'majonezë, mozzarella, ton, kërpudhë',
    descriptionEn: 'gourmet mayonnaise, rich mozzarella, high-grade bonito tuna, sautéed mushroom slices',
    priceSq: 230,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1600891/pexels-photo-1600891.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 'sand-mix',
    nameEn: 'Ultimate Mix Sandwich',
    nameSq: 'Sandwich Mix',
    descriptionSq: 'majonezë, domate, ullinj, mozzarella, ton, sallam pikant, kërpudhë',
    descriptionEn: 'savory mayo, tomato, olives, mozzarella, bonito tuna chunks, spicy salami, grilled mushrooms',
    priceSq: 250,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1600891/pexels-photo-1600891.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['Më i Ploti'],
    tagsEn: ['Mega Mix'],
    isPopular: true
  },
  {
    id: 'sand-vegjetarian',
    nameEn: 'Vegetarian Delight Sandwich',
    nameSq: 'Sandwich Vegjetarian',
    descriptionSq: 'majonezë, mozzarella, domate, ullinj, kërpudhë',
    descriptionEn: 'veggie mayo, cream mozzarella, freshly cut tomatoes, black olives, forest mushrooms',
    priceSq: 200,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/580612/pexels-photo-580612.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['Kopshti'],
    tagsEn: ['Healthy Garden']
  },
  {
    id: 'sand-chicken',
    nameEn: 'Crispy Chicken Fillet Sandwich',
    nameSq: 'Sandwich Chicken',
    descriptionSq: 'fileto pule, majonezë, mozzarella, domate, ullinj',
    descriptionEn: 'freshly roasted chicken breast strips, mayonnaise, soft mozzarella, ripe tomatoes, olives',
    priceSq: 250,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1199960/pexels-photo-1199960.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['Fileto Pule'],
    tagsEn: ['High Protein'],
    isPopular: true
  },
  {
    id: 'sand-proshute-krudo',
    nameEn: 'True Prosciutto Crudo Sandwich',
    nameSq: 'Sandwich Proshutë Krudo',
    descriptionSq: 'majonezë, mozzarella, proshutë krudo, domate, ullinj',
    descriptionEn: 'creamy mayonnaise, soft melting mozzarella, premium dry-cured prosciutto crudo, tomatoes, sliced olives',
    priceSq: 280,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['Mbreti Krudo'],
    tagsEn: ['Authentic Italian']
  },
  {
    id: 'sand-proshute-krudo-kerpudhe',
    nameEn: 'Crudo Prosciutto & Mushroom Sandwich',
    nameSq: 'Sandwich Proshutë Krudo & Kërpudhë',
    descriptionSq: 'majonezë, mozzarella, proshutë krudo, kërpudhë',
    descriptionEn: 'light mayonnaise, mozzarella, premium prosciutto crudo, tender white button mushrooms',
    priceSq: 300,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1600891/pexels-photo-1600891.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 'sand-tartufo',
    nameEn: 'Elite Tartufo & Crudo Sandwich',
    nameSq: 'Sandwich Tartufo',
    descriptionSq: 'salcë tartufi, proshutë krudo, kërpudhë, mozzarella, majonezë',
    descriptionEn: 'rich black truffle sauce base, prime prosciutto crudo, field mushrooms, mozzarella, mayonnaise',
    priceSq: 300,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['Truf i Zi'],
    tagsEn: ['Truffle Heaven'],
    isPopular: true
  },
  {
    id: 'sand-tersina',
    nameEn: 'Tersina Special Truffle Sandwich',
    nameSq: 'Sandwich Tersina',
    descriptionSq: 'salcë tartufi, peperoni, kërpudhë, mozzarella, majonezë',
    descriptionEn: 'premium black truffle cream, hot pepperoni curls, grilled mushrooms, melted mozzarella, mayo',
    priceSq: 300,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 'sand-pro-special',
    nameEn: 'PRO Sandwich Max',
    nameSq: 'PRO Sandwich',
    descriptionSq: 'majonezë, proshutë, mozzarella, djathë i bardhë, domate, pana',
    descriptionEn: 'mayonnaise, cooked ham, melting mozzarella, traditional soft white cheese, tomatoes, rich heavy cream',
    priceSq: 250,
    category: 'sandwiches',
    image: 'https://images.pexels.com/photos/1209029/pexels-photo-1209029.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsSq: ['Më i Shijshmi'],
    tagsEn: ['Supreme Choice']
  },

  // --- REFRESHMENTS (Drinks) ---
  {
    id: 'drink-cola',
    nameEn: 'Coca-Cola (0.33l)',
    nameSq: 'Koka-Kola (0.33l)',
    descriptionEn: 'Original taste, icy cold canned soda.',
    descriptionSq: 'Shije origjinale, pije freskuese e konservuar e ftohtë akull.',
    priceSq: 150,
    category: 'drinks',
    image: 'https://images.pexels.com/photos/3826278/pexels-photo-3826278.jpeg?auto=compress&cs=tinysrgb&w=600',
    tagsEn: ['Ice Cold'],
    tagsSq: ['Akull e Ftohtë']
  },
  {
    id: 'drink-fanta',
    nameEn: 'Fanta Orange (0.33l)',
    nameSq: 'Fanta Portokall (0.33l)',
    descriptionEn: 'Bright and sparkling orange soda.',
    descriptionSq: 'Pije gazuar me shije fantastike portokalli.',
    priceSq: 150,
    category: 'drinks',
    image: 'https://images.pexels.com/photos/97085/pexels-photo-97085.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 'drink-water',
    nameEn: 'Spring Water (0.5l)',
    nameSq: 'Ujë Burimi (0.5l)',
    descriptionEn: 'Pure mountain non-sparkling spring water.',
    descriptionSq: 'Ujë i pastër natyral burimi i freskët malor.',
    priceSq: 100,
    category: 'drinks',
    image: 'https://images.pexels.com/photos/407041/pexels-photo-407041.jpeg?auto=compress&cs=tinysrgb&w=600'
  },
  {
    id: 'drink-korca',
    nameEn: 'Korca Premium Beer (0.33l)',
    nameSq: 'Birrë Korça (0.33l)',
    descriptionEn: 'The traditional premium blonde Albanian lager, crisp & refreshing.',
    descriptionSq: 'Birra tradicionale shqiptare, bjonde e freskët me shije unike.',
    priceSq: 200,
    category: 'drinks',
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Birra_Korca.jpg',
    tagsEn: ['Local Favorite'],
    tagsSq: ['E Preferuara Vendase']
  }
];

export const REVIEWS = [
  {
    id: 'rev-1',
    author: 'Albix 90',
    type: 'Local Guide',
    count: '136 vlerësime • 164 foto',
    rating: 5,
    dateEn: '8 months ago',
    dateSq: 'Para 8 muajsh',
    commentEn: 'It doesn’t only look good, its tasty and it has a perfect woodfire crisp to it. Simply delicious.',
    commentSq: 'Nuk duket vetëm mirë, është jashtëzakonisht e shijshme dhe pjekja me dru bën diferencën sa i takon krustës!'
  },
  {
    id: 'rev-2',
    author: 'Gledis Basha',
    type: 'Verified Local',
    count: '4 vlerësime',
    rating: 5,
    dateEn: '2 years ago',
    dateSq: 'Para 2 vitesh',
    commentEn: 'The food is super delicious, fresh and has very good premium ingredients. Fast delivery in Yzberisht!',
    commentSq: 'Ushqimi është mjaft i shijshëm, i freskët dhe me përbërës mjaft cilësorë. Transport i shpejtë (20-25min).'
  },
  {
    id: 'rev-3',
    author: 'Fiona Hoxha',
    type: 'Local Guide',
    count: '42 vlerësime • 10 foto',
    rating: 5,
    dateEn: '3 months ago',
    dateSq: 'Para 3 muajsh',
    commentEn: 'Hands down the best crust and ingredients in the area. Try Pizza Primavera and the Tartufo sandwich, absolutely perfect.',
    commentSq: 'Pa diskutim picat më fantastike në këtë zonë. Këshilloj Pica Primavera dhe sandwich me Tartufo, janë perfektë.'
  }
];

export const TRANSLATIONS: Record<'en' | 'sq', TranslationSet> = {
  en: {
    appName: 'Pizza Italia',
    tagline: 'Authentic Italian Pizzeria',
    subtitle: 'Classic woodfire flavored pizzas and premium toasted artisan sandwiches in Yzberisht, Tirana. Slowly fermented crust cooked at 450°C for the ultimate airy crisp.',
    orderNow: 'Order Now & Choose Menu',
    viewDirections: 'See Location & Directions',
    ourMenu: 'Pizza Italia Menu',
    menuSubtitle: 'Woodfire Neapolitan Pizzas, Pressed Gourmet Sandwiches, and Icy Refreshments.',
    popular: 'House Favorite',
    price: 'Price',
    sizeMedium: 'Medium (Mesme)',
    sizeFamily: 'Family Size (Familjare)',
    addToCart: 'Add to Basket',
    added: 'Added to Basket ✓',
    yourCart: 'Your Customized Ticket',
    emptyCart: 'Your basket is currently empty. Explore the columns of Italy to start selecting!',
    cartTotal: 'Real-time Cost Summary',
    sendToWhatsApp: 'Deliver Order via WhatsApp Direct',
    requestingGPS: 'Locking GPS Coordinates via Satellite...',
    gpsAcquired: 'Live Location Linked ✓',
    gpsFailed: 'GPS was denied. Please fill in physical coordinates below.',
    locationRequired: 'Location Coordinates & Logistics',
    addressPlaceholder: 'Street, Building number, entrance details, landmarks for the courier in Tirana...',
    addressLabel: 'Delivery Info / Detailed Physical Address',
    getGPSBtn: 'Acquire Live GPS (Ensures Safe Delivery)',
    quickNotice: 'Open • Order Delivery between 10:00 AM - 12:00 AM',
    hours: 'Monday - Sunday • 10:00 AM - 12:00 AM (Midnight)',
    contactUs: 'Quick Orders Line',
    reviewsTitle: 'Customer Hearts (4.7 ★★★★★)',
    findUs: 'Find Us In Tirana',
    woltOrder: 'Find us on Wolt app',
    phoneLabel: 'Direct Dial Line',
    customerNameLabel: 'Your Customer Name',
    customerNamePlaceholder: 'e.g. Alban Hoxha',
    deliveryMethodLabel: 'Select Delivery Protocol',
    deliveryOption: 'Home Delivery',
    takeoutOption: 'Store Takeout',
    dineInOption: 'Dine-In Table',
    pizzaSection: 'Woodfire Pizzas 🍕',
    sandwichSection: 'Artisan Pressed Sandwiches 🥪',
    drinksSection: 'Cold Drinks 🥤',
    allSection: 'Full Menu',
    customIngredientsNotice: '*Extra additions: +30 Lekë for sandwiches, +50 Lekë for medium pizzas, +100 Lekë for family pizzas.'
  },
  sq: {
    appName: 'Pizza Italia',
    tagline: 'Pizzeri Autentike Italiane',
    subtitle: 'Pica me shije autentike furre me dru dhe sanduiçë artizanalë të pjekur në tostierë, në Yzberisht, Tiranë. Brumë i dytë i fermentuar në temperaturë optimale për krokante dhe butësi perfekte.',
    orderNow: 'Porosit Tani dhe Shiko Menunë',
    viewDirections: 'Shiko Adresën dhe Drejtimet',
    ourMenu: 'Menuja e Pica Italia',
    menuSubtitle: 'Pica Napolitane me Dru, Sanduiçë të Shtypur Gustatorë dhe Pije të Ftohta.',
    popular: 'E Preferuar',
    price: 'Çmimi',
    sizeMedium: 'E Mesme',
    sizeFamily: 'Familjare',
    addToCart: 'Shto në Shportë',
    added: 'Shtuar në Shportë ✓',
    yourCart: 'Shporta Juaj e Porosisë',
    emptyCart: 'Shporta juaj është bosh. Shfletoni menunë tonë fantastike dhe shtoni produktet tuaja të preferuara!',
    cartTotal: 'Totali i Amortizuar në Kohë Reale',
    sendToWhatsApp: 'Dërgo Porosinë Sigurt në WhatsApp',
    requestingGPS: 'Duke marrë koordinatat tuaja GPS...',
    gpsAcquired: 'Vendndodhja GPS u Regjistrua ✓',
    gpsFailed: 'Leja për GPS u refuzua. Shkruani adresën fizike më poshtë.',
    locationRequired: 'Vendndodhja dhe Logjistika e Transportit',
    addressPlaceholder: 'Rruga, numri i pallatit, hyrja, kati ose pikat referuese pranë zonës suaj për korrierin...',
    addressLabel: 'Adresa e Detajuar e Dorëzimit',
    getGPSBtn: 'Eksporto GPS-in Live (Garanton Dorëzim të Shpejtë)',
    quickNotice: 'Hapur • Shërbim Taksi - Falas 10:00 - 24:00',
    hours: 'E Hënë - E Dielë • 10:00 - 24:00 (Mesnatë)',
    contactUs: 'Linja e Shpejtë e Porosive',
    reviewsTitle: 'Dashuria e Klientëve tanë (4.7 ★★★★★)',
    findUs: 'Ku Ndodhemi në Tiranë',
    woltOrder: 'Na gjeni në Wolt',
    phoneLabel: 'Telefono Direkte',
    customerNameLabel: 'Emri Juaj',
    customerNamePlaceholder: 'p.sh. Alban Hoxha',
    deliveryMethodLabel: 'Zgjidhni Mënyrën e Marres',
    deliveryOption: 'Dërgesë në Shtëpi',
    takeoutOption: 'Merre Vetë (Takeout)',
    dineInOption: 'Në Pizzeri (Dine-In)',
    pizzaSection: 'Pica me Furrë Druri 🍕',
    sandwichSection: 'Sanduiçë të Shtypur Artizanalë 🥪',
    drinksSection: 'Pije Freskuese 🥤',
    allSection: 'E Gjithë Menuja',
    customIngredientsNotice: '*Shtesat: +30 lekë për sanduiçët, +50 lekë për picat e mesme, +100 lekë për picat familjare.'
  }
};
